apiVersion: apps/v1
kind: Deployment

metadata:
  name: admin-server
  labels:
    app: admin-server

spec:
  replicas: 1

  selector:
    matchLabels:
      app: admin-server

  template:
    metadata:
      labels:
        app: admin-server

    spec:

      initContainers:
        - name: wait-for-config-server
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until wget -qO- http://config-server:8888/actuator/health; do echo waiting for config-server; sleep 5; done"
            ]

        - name: wait-for-discovery-server
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until wget -qO- http://discovery-server:8761/actuator/health; do echo waiting for discovery-server; sleep 5; done"
            ]

      containers:
        - name: admin-server

          image: bhupendrabhati/admin-server:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 9091

          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka"

            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "300m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9091

            initialDelaySeconds: 40
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9091

            initialDelaySeconds: 90
            periodSeconds: 20

---
apiVersion: v1
kind: Service

metadata:
  name: admin-server

spec:
  selector:
    app: admin-server

  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091

  type: ClusterIP