apiVersion: apps/v1
kind: Deployment

metadata:
  name: visits-service
  labels:
    app: visits-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: visits-service

  template:
    metadata:
      labels:
        app: visits-service

    spec:

      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until wget -qO- http://discovery-server:8761/actuator/health; do echo waiting for discovery-server; sleep 5; done"
            ]

        - name: wait-for-mysql
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z mysql 3306; do echo waiting for mysql; sleep 5; done"
            ]

      containers:
        - name: visits-service

          image: bhupendrabhati/visits-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8083

          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka"

            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/petclinic?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password

            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
              
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "300m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083

            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083

            initialDelaySeconds: 300
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 10